apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperd-mpp-deployment
  labels:
    app: hyperd-mpp
    role: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hyperd-mpp
      role: worker
  template:
    metadata:
      labels:
        app: hyperd-mpp
        role: worker
    spec:
      containers:
      - name: hyperd-worker
        image: tfoldi/tableau-hyperd-docker
        ports:
        - containerPort: 7483

