apiVersion: v1
kind: Service
metadata:
  name: postgres-master
  labels:
    app: hyperd-mpp
    role: master
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: hyperd-mpp
    role: master
